services:
  server:
    build:
      context: .
      target: final
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_DATABASE}
      - PORT=${API_PORT}
      # - GOMEMLIMIT=
    ports:
      - ${API_PORT}:${API_PORT}
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    expose:
      - 5432
    ports:
      - ${DB_PORT}:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${DB_DATABASE}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db_data:
